CREATE OR REPLACE PACKAGE PA_VENTAS IS
    FUNCTION FU_EXISTENCIA_ORDEN(P_ID_ORDEN IN SALES_ORDER.ORDER_ID%TYPE) RETURN BOOLEAN;
    PROCEDURE PR_ALTA_ITEM(P_NOMBRE_PRODUCTO IN PRODUCT.DESCRIPTION%TYPE, P_ID_ORDEN IN SALES_ORDER.ORDER_ID%TYPE, P_CANTIDAD IN ITEM.QUANTITY%TYPE);
    PROCEDURE PR_LISTAR_CLIENTE;
    PROCEDURE PR_LISTAR_CLIENTE(P_ID_CLIENTE CUSTOMER.CUSTOMER_ID%TYPE);
END PA_VENTAS;
/

CREATE OR REPLACE PACKAGE BODY PA_VENTAS IS

-- Función 1: COUNT(*) siempre devuelve un valor numérico, incluso si no existen registros
-- Por esta razón, no es necesario manejar la excepción NO_DATA_FOUND
FUNCTION FU_EXISTENCIA_ORDEN(P_ID_ORDEN IN SALES_ORDER.ORDER_ID%TYPE)
RETURN BOOLEAN
IS
    V_CANT NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_CANT FROM SALES_ORDER WHERE ORDER_ID = P_ID_ORDEN;

    IF V_CANT > 0 THEN
        RETURN TRUE;
    ELSE
        RETURN FALSE;
    END IF;
    
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('(FU_EXISTENCIA_ORDEN) Error: '||SQLCODE||' - Mensaje: '||SQLERRM);
        RETURN FALSE;
END FU_EXISTENCIA_ORDEN;

-- Funcion 3 (privada)
FUNCTION FU_ID_PRODUCTO(P_NOMBRE_PRODUCTO IN PRODUCT.DESCRIPTION%TYPE) RETURN PRODUCT.PRODUCT_ID%TYPE
IS
    V_ID_PRODUCTO PRODUCT.PRODUCT_ID%TYPE;

BEGIN
    SELECT PRODUCT_ID INTO V_ID_PRODUCTO FROM PRODUCT WHERE UPPER(DESCRIPTION) = UPPER(P_NOMBRE_PRODUCTO);
    RETURN V_ID_PRODUCTO;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20001, '(FU_ID_PRODUCTO) No existe un producto con la descripción ingresada');

    WHEN TOO_MANY_ROWS THEN
        RAISE_APPLICATION_ERROR(-20002, '(FU_ID_PRODUCTO) Existe más de un producto con la descripción ingresada');

    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20003, '(FU_ID_PRODUCTO) Error: '||SQLCODE||' - Mensaje: '||SQLERRM);

END FU_ID_PRODUCTO;

-- Procedimiento 2
PROCEDURE PR_ALTA_ITEM(P_NOMBRE_PRODUCTO IN PRODUCT.DESCRIPTION%TYPE, P_ID_ORDEN IN SALES_ORDER.ORDER_ID%TYPE, P_CANTIDAD IN ITEM.QUANTITY%TYPE)
IS
    V_RES BOOLEAN;
    V_MAX_ID_ITEM ITEM.ITEM_ID%TYPE;
    V_ID_ITEM ITEM.ITEM_ID%TYPE;
    V_ID_PRODUCTO PRODUCT.PRODUCT_ID%TYPE;
    V_PRECIO PRICE.LIST_PRICE%TYPE;
    E_PRODUCTO_NO_EXISTE EXCEPTION; PRAGMA EXCEPTION_INIT(E_PRODUCTO_NO_EXISTE, -20001);
    E_PRODUCTO_DUPLICADO EXCEPTION; PRAGMA EXCEPTION_INIT(E_PRODUCTO_DUPLICADO, -20002);
    E_ERROR_PRODUCTO EXCEPTION; PRAGMA EXCEPTION_INIT(E_ERROR_PRODUCTO, -20003);

BEGIN
    V_RES := FU_EXISTENCIA_ORDEN(P_ID_ORDEN);
    IF V_RES THEN
        -- Cálculo del ITEM_ID del ítem a agregar
        SELECT NVL(MAX(ITEM_ID),0) INTO V_MAX_ID_ITEM FROM ITEM WHERE ORDER_ID = P_ID_ORDEN;
        V_ID_ITEM := V_MAX_ID_ITEM+1;

        -- Cálculo del PRODUCT_ID del item a agregar
        V_ID_PRODUCTO := FU_ID_PRODUCTO(P_NOMBRE_PRODUCTO);

        -- Selección del precio del ítem
        SELECT LIST_PRICE INTO V_PRECIO FROM PRICE WHERE PRODUCT_ID = V_ID_PRODUCTO AND START_DATE <= SYSDATE AND (END_DATE IS NULL OR END_DATE >= SYSDATE);

        -- Inserción en la tabla ITEM
        INSERT INTO ITEM(ORDER_ID, ITEM_ID, PRODUCT_ID, ACTUAL_PRICE, QUANTITY, TOTAL) VALUES(P_ID_ORDEN, V_ID_ITEM, V_ID_PRODUCTO, V_PRECIO, P_CANTIDAD, V_PRECIO*P_CANTIDAD);

        IF SQL%ROWCOUNT>0 THEN
            DBMS_OUTPUT.PUT_LINE('Se ha realizado la insercion');
        END IF;

    ELSE
        DBMS_OUTPUT.PUT_LINE('No se ha realizado la insercion');
    END IF;

EXCEPTION
    WHEN E_PRODUCTO_NO_EXISTE THEN
        DBMS_OUTPUT.PUT_LINE('Error: '||SQLCODE||' - Mensaje: '||SQLERRM);

    WHEN E_PRODUCTO_DUPLICADO THEN
        DBMS_OUTPUT.PUT_LINE('Error: '||SQLCODE||' - Mensaje: '||SQLERRM);

    WHEN E_ERROR_PRODUCTO THEN
        DBMS_OUTPUT.PUT_LINE('Error: '||SQLCODE||' - Mensaje: '||SQLERRM);

    WHEN TOO_MANY_ROWS THEN
        DBMS_OUTPUT.PUT_LINE('(PR_ALTA_ITEM) Se encontraron varios precios vigentes para el producto ingresado');

    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('(PR_ALTA_ITEM) No existe un precio vigente para el producto');

    WHEN DUP_VAL_ON_INDEX THEN
        DBMS_OUTPUT.PUT_LINE('(PR_ALTA_ITEM) Ya existe un ítem con ese ID para la orden ingresada');

    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('(PR_ALTA_ITEM) Error en el tipo o valor de alguno de los datos ingresados');

    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('(PR_ALTA_ITEM) Error: '||SQLCODE||' - Mensaje: '||SQLERRM);

END PR_ALTA_ITEM;

-- Procedimiento 4
PROCEDURE PR_LISTAR_CLIENTE(P_ID_CLIENTE IN CUSTOMER.CUSTOMER_ID%TYPE) IS
    CURSOR C_CURSOR_A IS SELECT ORDER_ID AS ID_ORDEN, ORDER_DATE AS FECHA_ORDEN, TOTAL FROM SALES_ORDER WHERE CUSTOMER_ID = P_ID_CLIENTE ORDER BY ORDER_ID;
    CURSOR C_CURSOR_B(P_ID_ORDEN SALES_ORDER.ORDER_ID%TYPE) IS SELECT I.ITEM_ID AS ID_ITEM, P.DESCRIPTION AS DESCRIPCION, I.ACTUAL_PRICE AS PRECIO_ACTUAL, I.QUANTITY AS CANTIDAD, I.TOTAL
    FROM ITEM I, PRODUCT P WHERE I.PRODUCT_ID = P.PRODUCT_ID AND I.ORDER_ID = P_ID_ORDEN ORDER BY I.ITEM_ID;
    NOMBRE_CLIENTE CUSTOMER.NAME%TYPE; 
    NOMBRE_VENDEDOR EMPLOYEE.FIRST_NAME%TYPE; APELLIDO_VENDEDOR EMPLOYEE.LAST_NAME%TYPE;
    CANTIDAD_ORDENES NUMBER := 0;

BEGIN
    SELECT C.NAME, E.FIRST_NAME, E.LAST_NAME INTO NOMBRE_CLIENTE, NOMBRE_VENDEDOR, APELLIDO_VENDEDOR FROM CUSTOMER C, EMPLOYEE E WHERE C.CUSTOMER_ID = P_ID_CLIENTE AND C.SALESPERSON_ID = E.EMPLOYEE_ID;
    DBMS_OUTPUT.PUT_LINE('Nombre cliente: '||NOMBRE_CLIENTE||' - Nombre vendedor: '||NOMBRE_VENDEDOR||' '||APELLIDO_VENDEDOR);

    SELECT COUNT(*) INTO CANTIDAD_ORDENES FROM SALES_ORDER WHERE CUSTOMER_ID = P_ID_CLIENTE;
    
    IF CANTIDAD_ORDENES = 0 THEN
        DBMS_OUTPUT.PUT_LINE('El cliente no posee compras registradas');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Cantidad de órdenes: '||CANTIDAD_ORDENES);
        FOR R_CURSOR_A IN C_CURSOR_A LOOP
            DBMS_OUTPUT.PUT_LINE('ID Orden: '||R_CURSOR_A.ID_ORDEN||' - Fecha: '||R_CURSOR_A.FECHA_ORDEN||' - Total: '||R_CURSOR_A.TOTAL);
            FOR R_CURSOR_B IN C_CURSOR_B(R_CURSOR_A.ID_ORDEN) LOOP
                DBMS_OUTPUT.PUT_LINE('ID Item: '||R_CURSOR_B.ID_ITEM||' - Descripcion: '||R_CURSOR_B.DESCRIPCION||' - Precio actual: '||R_CURSOR_B.PRECIO_ACTUAL||' - Cantidad: '||R_CURSOR_B.CANTIDAD||' - Total: '||R_CURSOR_B.TOTAL);
            END LOOP;
            DBMS_OUTPUT.PUT_LINE(' ');
        END LOOP;
    END IF;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('(PR_LISTAR_CLIENTE) No se encontró información asociada al cliente ingresado');

    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('(PR_LISTAR_CLIENTE) Error en el tipo o valor de alguno de los datos ingresados');

    WHEN TOO_MANY_ROWS THEN
        DBMS_OUTPUT.PUT_LINE('(PR_LISTAR_CLIENTE) Se encontraron múltiples registros para el cliente ingresado');

    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('(PR_LISTAR_CLIENTE) Error: '||SQLCODE||' - Mensaje: '||SQLERRM);

END PR_LISTAR_CLIENTE;

-- Procedimiento 4 sobrecargado: al no recibir ID, lista todos los clientes
PROCEDURE PR_LISTAR_CLIENTE IS
    CURSOR C_CLIENTES IS SELECT CUSTOMER_ID FROM CUSTOMER ORDER BY CUSTOMER_ID;
BEGIN
    FOR R_CLIENTE IN C_CLIENTES LOOP
        DBMS_OUTPUT.PUT_LINE('Cliente ID: '||R_CLIENTE.CUSTOMER_ID);
        PR_LISTAR_CLIENTE(R_CLIENTE.CUSTOMER_ID);
        DBMS_OUTPUT.PUT_LINE(' ');
    END LOOP;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('(PR_LISTAR_CLIENTE) Error: '||SQLCODE||' - Mensaje: '||SQLERRM);
END PR_LISTAR_CLIENTE;

END PA_VENTAS;
/